//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeExamNotice
    {
        public int CollegeExamNoticeID { get; set; }
        public string ExamCode { get; set; }
        public string Degree { get; set; }
        public string Semester { get; set; }
        public Nullable<int> ExamFees { get; set; }
        public Nullable<int> OtherFees { get; set; }
        public Nullable<int> TutionFees { get; set; }
        public Nullable<int> UnivCode { get; set; }
        public Nullable<int> CollegeCode { get; set; }
    }
}
