//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoUni.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentDetail
    {
        public int STUD_ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string StudentName { get; set; }
        public string Semester { get; set; }
        public string Department { get; set; }
        public string EmailID { get; set; }
        public string Mobile { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string JoiningYear { get; set; }
        public string CompletionYear { get; set; }
        public string CollegeCode { get; set; }
        public string UniversityCode { get; set; }
    }
}
