//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int Subject_ID { get; set; }
        public string Degree { get; set; }
        public Nullable<int> Department_Code { get; set; }
        public string Department { get; set; }
        public string Semester { get; set; }
        public string SubjectCode { get; set; }
        public string Subjects { get; set; }
    }
}
