//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityDetail
    {
        public int UniversityID { get; set; }
        public string UniversityCode { get; set; }
        public string UniversityName { get; set; }
        public string Username { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
    }
}
